// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: editorevent.proto

package edu.umich.jgracik_zhuwei.eecs441.wewrite;

public final class EditorEventProto {
  private EditorEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EditorEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 beginIndex = 1;
    /**
     * <code>optional int32 beginIndex = 1;</code>
     */
    boolean hasBeginIndex();
    /**
     * <code>optional int32 beginIndex = 1;</code>
     */
    int getBeginIndex();

    // optional string oldText = 2;
    /**
     * <code>optional string oldText = 2;</code>
     */
    boolean hasOldText();
    /**
     * <code>optional string oldText = 2;</code>
     */
    java.lang.String getOldText();
    /**
     * <code>optional string oldText = 2;</code>
     */
    com.google.protobuf.ByteString
        getOldTextBytes();

    // optional string newText = 3;
    /**
     * <code>optional string newText = 3;</code>
     */
    boolean hasNewText();
    /**
     * <code>optional string newText = 3;</code>
     */
    java.lang.String getNewText();
    /**
     * <code>optional string newText = 3;</code>
     */
    com.google.protobuf.ByteString
        getNewTextBytes();

    // required int32 newCursorIdx = 4;
    /**
     * <code>required int32 newCursorIdx = 4;</code>
     */
    boolean hasNewCursorIdx();
    /**
     * <code>required int32 newCursorIdx = 4;</code>
     */
    int getNewCursorIdx();

    // required int64 userid = 5;
    /**
     * <code>required int64 userid = 5;</code>
     */
    boolean hasUserid();
    /**
     * <code>required int64 userid = 5;</code>
     */
    long getUserid();
  }
  /**
   * Protobuf type {@code edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEvent}
   */
  public static final class EditorEvent extends
      com.google.protobuf.GeneratedMessage
      implements EditorEventOrBuilder {
    // Use EditorEvent.newBuilder() to construct.
    private EditorEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EditorEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EditorEvent defaultInstance;
    public static EditorEvent getDefaultInstance() {
      return defaultInstance;
    }

    public EditorEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EditorEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              beginIndex_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              oldText_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              newText_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              newCursorIdx_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              userid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent.class, edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<EditorEvent> PARSER =
        new com.google.protobuf.AbstractParser<EditorEvent>() {
      public EditorEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EditorEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EditorEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 beginIndex = 1;
    public static final int BEGININDEX_FIELD_NUMBER = 1;
    private int beginIndex_;
    /**
     * <code>optional int32 beginIndex = 1;</code>
     */
    public boolean hasBeginIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 beginIndex = 1;</code>
     */
    public int getBeginIndex() {
      return beginIndex_;
    }

    // optional string oldText = 2;
    public static final int OLDTEXT_FIELD_NUMBER = 2;
    private java.lang.Object oldText_;
    /**
     * <code>optional string oldText = 2;</code>
     */
    public boolean hasOldText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string oldText = 2;</code>
     */
    public java.lang.String getOldText() {
      java.lang.Object ref = oldText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          oldText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string oldText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOldTextBytes() {
      java.lang.Object ref = oldText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string newText = 3;
    public static final int NEWTEXT_FIELD_NUMBER = 3;
    private java.lang.Object newText_;
    /**
     * <code>optional string newText = 3;</code>
     */
    public boolean hasNewText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string newText = 3;</code>
     */
    public java.lang.String getNewText() {
      java.lang.Object ref = newText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string newText = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNewTextBytes() {
      java.lang.Object ref = newText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 newCursorIdx = 4;
    public static final int NEWCURSORIDX_FIELD_NUMBER = 4;
    private int newCursorIdx_;
    /**
     * <code>required int32 newCursorIdx = 4;</code>
     */
    public boolean hasNewCursorIdx() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 newCursorIdx = 4;</code>
     */
    public int getNewCursorIdx() {
      return newCursorIdx_;
    }

    // required int64 userid = 5;
    public static final int USERID_FIELD_NUMBER = 5;
    private long userid_;
    /**
     * <code>required int64 userid = 5;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 userid = 5;</code>
     */
    public long getUserid() {
      return userid_;
    }

    private void initFields() {
      beginIndex_ = 0;
      oldText_ = "";
      newText_ = "";
      newCursorIdx_ = 0;
      userid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNewCursorIdx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, beginIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOldTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNewTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, newCursorIdx_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, userid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, beginIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOldTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNewTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, newCursorIdx_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, userid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent.class, edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent.Builder.class);
      }

      // Construct using edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        beginIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        oldText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        newText_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        newCursorIdx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        userid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_descriptor;
      }

      public edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent getDefaultInstanceForType() {
        return edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent.getDefaultInstance();
      }

      public edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent build() {
        edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent buildPartial() {
        edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent result = new edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.beginIndex_ = beginIndex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.oldText_ = oldText_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.newText_ = newText_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newCursorIdx_ = newCursorIdx_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userid_ = userid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent) {
          return mergeFrom((edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent other) {
        if (other == edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent.getDefaultInstance()) return this;
        if (other.hasBeginIndex()) {
          setBeginIndex(other.getBeginIndex());
        }
        if (other.hasOldText()) {
          bitField0_ |= 0x00000002;
          oldText_ = other.oldText_;
          onChanged();
        }
        if (other.hasNewText()) {
          bitField0_ |= 0x00000004;
          newText_ = other.newText_;
          onChanged();
        }
        if (other.hasNewCursorIdx()) {
          setNewCursorIdx(other.getNewCursorIdx());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNewCursorIdx()) {
          
          return false;
        }
        if (!hasUserid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEventProto.EditorEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 beginIndex = 1;
      private int beginIndex_ ;
      /**
       * <code>optional int32 beginIndex = 1;</code>
       */
      public boolean hasBeginIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 beginIndex = 1;</code>
       */
      public int getBeginIndex() {
        return beginIndex_;
      }
      /**
       * <code>optional int32 beginIndex = 1;</code>
       */
      public Builder setBeginIndex(int value) {
        bitField0_ |= 0x00000001;
        beginIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 beginIndex = 1;</code>
       */
      public Builder clearBeginIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        beginIndex_ = 0;
        onChanged();
        return this;
      }

      // optional string oldText = 2;
      private java.lang.Object oldText_ = "";
      /**
       * <code>optional string oldText = 2;</code>
       */
      public boolean hasOldText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string oldText = 2;</code>
       */
      public java.lang.String getOldText() {
        java.lang.Object ref = oldText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          oldText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string oldText = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOldTextBytes() {
        java.lang.Object ref = oldText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oldText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string oldText = 2;</code>
       */
      public Builder setOldText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        oldText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string oldText = 2;</code>
       */
      public Builder clearOldText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oldText_ = getDefaultInstance().getOldText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string oldText = 2;</code>
       */
      public Builder setOldTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        oldText_ = value;
        onChanged();
        return this;
      }

      // optional string newText = 3;
      private java.lang.Object newText_ = "";
      /**
       * <code>optional string newText = 3;</code>
       */
      public boolean hasNewText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string newText = 3;</code>
       */
      public java.lang.String getNewText() {
        java.lang.Object ref = newText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          newText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string newText = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNewTextBytes() {
        java.lang.Object ref = newText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string newText = 3;</code>
       */
      public Builder setNewText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        newText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string newText = 3;</code>
       */
      public Builder clearNewText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newText_ = getDefaultInstance().getNewText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string newText = 3;</code>
       */
      public Builder setNewTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        newText_ = value;
        onChanged();
        return this;
      }

      // required int32 newCursorIdx = 4;
      private int newCursorIdx_ ;
      /**
       * <code>required int32 newCursorIdx = 4;</code>
       */
      public boolean hasNewCursorIdx() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 newCursorIdx = 4;</code>
       */
      public int getNewCursorIdx() {
        return newCursorIdx_;
      }
      /**
       * <code>required int32 newCursorIdx = 4;</code>
       */
      public Builder setNewCursorIdx(int value) {
        bitField0_ |= 0x00000008;
        newCursorIdx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 newCursorIdx = 4;</code>
       */
      public Builder clearNewCursorIdx() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newCursorIdx_ = 0;
        onChanged();
        return this;
      }

      // required int64 userid = 5;
      private long userid_ ;
      /**
       * <code>required int64 userid = 5;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 userid = 5;</code>
       */
      public long getUserid() {
        return userid_;
      }
      /**
       * <code>required int64 userid = 5;</code>
       */
      public Builder setUserid(long value) {
        bitField0_ |= 0x00000010;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userid = 5;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userid_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEvent)
    }

    static {
      defaultInstance = new EditorEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:edu.umich.jgracik_zhuwei.eecs441.wewrite.EditorEvent)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021editorevent.proto\022(edu.umich.jgracik_z" +
      "huwei.eecs441.wewrite\"i\n\013EditorEvent\022\022\n\n" +
      "beginIndex\030\001 \001(\005\022\017\n\007oldText\030\002 \001(\t\022\017\n\007new" +
      "Text\030\003 \001(\t\022\024\n\014newCursorIdx\030\004 \002(\005\022\016\n\006user" +
      "id\030\005 \002(\003B\022B\020EditorEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_umich_jgracik_zhuwei_eecs441_wewrite_EditorEvent_descriptor,
              new java.lang.String[] { "BeginIndex", "OldText", "NewText", "NewCursorIdx", "Userid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
